import { createClient } from 'https://esm.sh/@supabase/supabase-js@2.57.4';

const corsHeaders = {
  'Access-Control-Allow-Origin': '*',
  'Access-Control-Allow-Headers': 'authorization, x-client-info, apikey, content-type, x-api-key',
};

Deno.serve(async (req) => {
  // Handle CORS preflight requests
  if (req.method === 'OPTIONS') {
    return new Response(null, { headers: corsHeaders });
  }

  try {
    // Verify API key
    const apiKey = req.headers.get('x-api-key');
    if (!apiKey) {
      return new Response(
        JSON.stringify({ error: 'API key required in X-API-Key header' }),
        { status: 401, headers: { ...corsHeaders, 'Content-Type': 'application/json' } }
      );
    }

    const supabase = createClient(
      Deno.env.get('SUPABASE_URL') ?? '',
      Deno.env.get('SUPABASE_SERVICE_ROLE_KEY') ?? ''
    );

    // Validate API key and get permissions
    const { data: apiKeyData, error: apiKeyError } = await supabase
      .from('api_keys')
      .select('user_id, permissions, active')
      .eq('api_key', apiKey)
      .eq('active', true)
      .maybeSingle();

    if (apiKeyError || !apiKeyData) {
      return new Response(
        JSON.stringify({ error: 'Invalid or inactive API key' }),
        { status: 401, headers: { ...corsHeaders, 'Content-Type': 'application/json' } }
      );
    }

    // Check permissions
    const permissions = apiKeyData.permissions as any;
    if (!permissions?.produtos?.write) {
      return new Response(
        JSON.stringify({ error: 'Insufficient permissions for this endpoint' }),
        { status: 403, headers: { ...corsHeaders, 'Content-Type': 'application/json' } }
      );
    }

    // Update last used timestamp
    await supabase
      .from('api_keys')
      .update({ last_used: new Date().toISOString() })
      .eq('api_key', apiKey);

    // Parse request body
    const body = await req.json();
    const {
      nome,
      descricao,
      preco,
      estoque,
      sku,
      gtin,
      categoria_id,
      imagens = [],
      marca,
      especificacoes = {},
      peso,
      largura,
      altura,
      comprimento
    } = body;

    // Validate required fields
    if (!nome || !preco) {
      return new Response(
        JSON.stringify({ 
          error: 'Campos obrigatórios: nome, preco',
          received: { nome, preco }
        }),
        { status: 400, headers: { ...corsHeaders, 'Content-Type': 'application/json' } }
      );
    }

    // Create product data
    const productData: any = {
      name: nome,
      description: descricao,
      price: preco,
      stock_quantity: estoque || 0,
      category_id: categoria_id,
      images: imagens,
      brand: marca,
      specifications: especificacoes,
      weight: peso,
      width: largura,
      height: altura,
      length: comprimento,
      active: true
    };

    // Add SKU and GTIN if provided, otherwise they will be auto-generated by trigger
    if (sku && sku.trim()) {
      productData.sku = sku.trim();
    }
    if (gtin && gtin.trim()) {
      productData.gtin_ean13 = gtin.trim();
    }

    // Insert product
    const { data: product, error: productError } = await supabase
      .from('products')
      .insert(productData)
      .select()
      .single();

    if (productError) {
      console.error('Error creating product:', productError);
      return new Response(
        JSON.stringify({ 
          error: 'Erro ao criar produto',
          details: productError.message 
        }),
        { status: 500, headers: { ...corsHeaders, 'Content-Type': 'application/json' } }
      );
    }

    return new Response(
      JSON.stringify({ 
        success: true,
        message: 'Produto criado com sucesso',
        data: {
          id: product.id,
          nome: product.name,
          sku: product.sku,
          gtin: product.gtin_ean13,
          preco: product.price,
          estoque: product.stock_quantity
        }
      }),
      { headers: { ...corsHeaders, 'Content-Type': 'application/json' } }
    );

  } catch (error) {
    console.error('Error in api-produtos-cadastrar:', error);
    return new Response(
      JSON.stringify({ error: 'Internal server error' }),
      { status: 500, headers: { ...corsHeaders, 'Content-Type': 'application/json' } }
    );
  }
});